import argparse
import json
import time
from pathlib import Path
from typing import Optional

from config import general_config, init_config, prompts_config
from .agent import VideoSeekAgent


def build_agent_config(args: argparse.Namespace) -> dict:
    config = {}
    config.update(general_config)
    config.update(prompts_config)
    config = init_config(config, args)
    if isinstance(config.get("tools"), str):
        config["tools"] = [item.strip() for item in config["tools"].split(",") if item.strip()]
    return config


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(prog="videoseek")
    p.add_argument("--video_path", required=True, help="YouTube URL or local path to video.")
    p.add_argument("--user_query", required=True, help="Question/query towards this video.")
    p.add_argument("--subtitle_path", default=None, help="Local path to subtitle file.")
    p.add_argument(
        "--output_dir",
        default="./output/",
        help="Directory to write outputs (default: ./output/).",
    )
    p.add_argument("--verbose", action="store_true", help="Print agent step logs.")
    p.add_argument("--tools", default=None, help="Comma-separated tool list, e.g. overview,skim,focus,focus_qwen.")

    # Allow overriding general.yaml keys (optional)
    p.add_argument("--model_name", default=general_config['model_name'], help="Model name.")
    p.add_argument("--api_base", default=general_config['api_base'], help="API base.")
    p.add_argument("--api_key", default=general_config['api_key'], help="API key.")
    p.add_argument("--api_version", default=general_config['api_version'], help="API version.")
    p.add_argument("--observer_model_name", default=general_config.get('observer_model_name'), help="Optional visual observer model for overview/skim/focus.")
    p.add_argument("--observer_api_base", default=general_config.get('observer_api_base'), help="Optional observer API base.")
    p.add_argument("--observer_api_key", default=general_config.get('observer_api_key'), help="Optional observer API key.")
    p.add_argument("--observer_api_version", default=general_config.get('observer_api_version'), help="Optional observer API version.")
    p.add_argument("--observer_reasoning_effort", default=general_config.get('observer_reasoning_effort'), help="Reasoning effort for observer model calls.")
    p.add_argument("--observer_backend", default=general_config.get('observer_backend'), choices=["api", "local_qwen", "hybrid"], help="Observer backend for visual tools.")
    p.add_argument("--local_qwen_tools", default=general_config.get('local_qwen_tools'), help="Comma-separated tools that use local Qwen when observer_backend=hybrid.")
    p.add_argument("--local_qwen_focus_modes", default=general_config.get('local_qwen_focus_modes'), help="Comma-separated focus modes allowed to use local Qwen in hybrid mode.")
    p.add_argument("--local_qwen_skim_modes", default=general_config.get('local_qwen_skim_modes'), help="Comma-separated skim modes allowed to use local Qwen in hybrid mode.")
    p.add_argument("--local_qwen_model_path", default=general_config.get('local_qwen_model_path'), help="Local Qwen2.5-VL model path.")
    p.add_argument("--local_qwen_python", default=general_config.get('local_qwen_python'), help="Optional Python executable for a local Qwen subprocess worker.")
    p.add_argument("--local_qwen_persistent_worker", action=argparse.BooleanOptionalAction, default=general_config.get('local_qwen_persistent_worker'), help="Keep one local Qwen subprocess alive across focus calls.")
    p.add_argument("--local_qwen_cuda_visible_devices", default=general_config.get('local_qwen_cuda_visible_devices'), help="CUDA_VISIBLE_DEVICES value for local Qwen, e.g. 5.")
    p.add_argument("--local_qwen_device_map", default=general_config.get('local_qwen_device_map'), help="Transformers device_map for local Qwen.")
    p.add_argument("--local_qwen_max_memory", default=general_config.get('local_qwen_max_memory'), help="Transformers max_memory, e.g. 0:34GiB after restricting visible devices.")
    p.add_argument("--local_qwen_torch_dtype", default=general_config.get('local_qwen_torch_dtype'), choices=["bfloat16", "float16"], help="Torch dtype for local Qwen.")
    p.add_argument("--local_qwen_max_new_tokens", type=int, default=general_config.get('local_qwen_max_new_tokens'), help="Max new tokens for local Qwen observations.")
    p.add_argument("--local_qwen_max_images", type=int, default=general_config.get('local_qwen_max_images'), help="Maximum images per local Qwen observation call.")
    p.add_argument("--local_qwen_max_image_side", type=int, default=general_config.get('local_qwen_max_image_side'), help="Resize local Qwen input images so their longest side is at most this many pixels.")
    p.add_argument("--local_qwen_timeout_s", type=int, default=general_config.get('local_qwen_timeout_s'), help="Timeout for local Qwen subprocess calls.")
    p.add_argument("--local_qwen_no_cpu_offload", action=argparse.BooleanOptionalAction, default=general_config.get('local_qwen_no_cpu_offload'), help="Reject local Qwen CPU/disk offload.")
    p.add_argument("--local_qwen_fallback_to_api", action=argparse.BooleanOptionalAction, default=general_config.get('local_qwen_fallback_to_api'), help="Fallback to API if local Qwen fails.")
    p.add_argument("--qwen_caption_only_output", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_caption_only_output'), help="Ask local Qwen for plain per-frame captions and structure them in Python.")
    p.add_argument("--reasoning_effort", default=general_config['reasoning_effort'], help="Reasoning effort of the LLM.")
    p.add_argument("--seed", type=int, default=general_config['seed'], help="Seed.")
    p.add_argument("--temperature", type=float, default=general_config['temperature'], help="Temperature.")
    p.add_argument("--max_tokens", type=int, default=general_config['max_tokens'], help="Max output tokens of the LLM.")
    p.add_argument("--max_steps", type=int, default=general_config['max_steps'], help="Max steps of the VideoSeek agent.")
    p.add_argument("--use_evidence_reducer", action=argparse.BooleanOptionalAction, default=general_config.get('use_evidence_reducer'), help="Group timestamped evidence by scene before final answer.")
    p.add_argument("--use_structured_evidence_state", action=argparse.BooleanOptionalAction, default=general_config.get('use_structured_evidence_state'), help="Compile tool observations into structured evidence items for planner/reducer prompts.")
    p.add_argument("--structured_evidence_max_items", type=int, default=general_config.get('structured_evidence_max_items'), help="Default maximum structured evidence items to show.")
    p.add_argument("--structured_evidence_prompt_max_items", type=int, default=general_config.get('structured_evidence_prompt_max_items'), help="Maximum structured evidence items shown to the planner.")
    p.add_argument("--structured_evidence_answer_max_items", type=int, default=general_config.get('structured_evidence_answer_max_items'), help="Maximum structured evidence items shown to the answer reducer.")
    p.add_argument("--structured_evidence_include_planner_state", action=argparse.BooleanOptionalAction, default=general_config.get('structured_evidence_include_planner_state'), help="Include compact investigation state in planner and answer prompts.")
    p.add_argument("--coseek1_compact_event_coverage", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_compact_event_coverage'), help="Expose one compact earliest/strongest evidence record per explicit event.")
    p.add_argument("--coseek1_compact_event_coverage_max_items", type=int, default=general_config.get('coseek1_compact_event_coverage_max_items'), help="Maximum explicit events in compact event coverage.")
    p.add_argument("--coseek1_event_coverage_inline_verify", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_event_coverage_inline_verify'), help="Batch explicit event anchors into one inline frame verification.")
    p.add_argument("--coseek1_event_coverage_inline_verify_max_windows", type=int, default=general_config.get('coseek1_event_coverage_inline_verify_max_windows'), help="Maximum event anchors in one inline verification.")
    p.add_argument("--coseek1_event_coverage_inline_verify_radius_s", type=float, default=general_config.get('coseek1_event_coverage_inline_verify_radius_s'), help="Context radius around each event anchor.")
    p.add_argument("--structured_evidence_include_occurrence_view", action=argparse.BooleanOptionalAction, default=general_config.get('structured_evidence_include_occurrence_view'), help="Reserved: include occurrence view when implemented.")
    p.add_argument("--structured_evidence_include_timeline_view", action=argparse.BooleanOptionalAction, default=general_config.get('structured_evidence_include_timeline_view'), help="Reserved: include timeline view when implemented.")
    p.add_argument("--structured_evidence_include_object_state_view", action=argparse.BooleanOptionalAction, default=general_config.get('structured_evidence_include_object_state_view'), help="Reserved: include object-state view when implemented.")
    p.add_argument("--structured_evidence_preserve_aggregate_verifier_decision", action=argparse.BooleanOptionalAction, default=general_config.get('structured_evidence_preserve_aggregate_verifier_decision'), help="Preserve a complete frame-verifier option comparison beside timestamp facts.")
    p.add_argument("--coseek1_candidate_frontier", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_candidate_frontier'), help="Expose the persistent candidate frontier to the planner.")
    p.add_argument("--coseek1_candidate_frontier_max_items", type=int, default=general_config.get('coseek1_candidate_frontier_max_items'), help="Maximum candidate frontier items shown to the planner.")
    p.add_argument("--coseek1_evidence_episode_frontier", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_evidence_episode_frontier'), help="Expose the persistent Evidence Episode Frontier.")
    p.add_argument("--coseek1_evidence_episode_max_items", type=int, default=general_config.get('coseek1_evidence_episode_max_items'), help="Maximum episode items shown to the planner.")
    p.add_argument("--coseek1_episode_anchor_radius_s", type=float, default=general_config.get('coseek1_episode_anchor_radius_s'), help="Radius around query-relevant timestamp anchors.")
    p.add_argument("--coseek1_episode_focus_window_s", type=float, default=general_config.get('coseek1_episode_focus_window_s'), help="Maximum duration treated as a precise episode.")
    p.add_argument("--coseek1_episode_broad_window_s", type=float, default=general_config.get('coseek1_episode_broad_window_s'), help="Minimum broad range redirected from frame_verify to skim_qwen.")
    p.add_argument("--coseek1_episode_backend_router", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_episode_backend_router'), help="Repair observation backend/window granularity mismatches.")
    p.add_argument("--coseek1_answer_evidence_audit", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_answer_evidence_audit'), help="Record non-blocking answer provenance audit.")
    p.add_argument("--coseek1_frontier_timestamp_cues", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_frontier_timestamp_cues'), help="Promote timestamp observations with explicit open questions into frontier candidates.")
    p.add_argument("--coseek1_frontier_timestamp_cue_radius_s", type=float, default=general_config.get('coseek1_frontier_timestamp_cue_radius_s'), help="Context radius around promoted timestamp cues.")
    p.add_argument("--coseek1_frontier_evidence_scope", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_frontier_evidence_scope'), help="Annotate evidence as local timestamp/window or global routing context.")
    p.add_argument("--coseek1_persistent_candidate_pool", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_persistent_candidate_pool'), help="Merge Overview scenes and query-relevant timestamp cues into a stable candidate pool.")
    p.add_argument("--coseek1_persistent_candidate_pool_max_items", type=int, default=general_config.get('coseek1_persistent_candidate_pool_max_items'), help="Maximum persistent candidates shown to the planner.")
    p.add_argument("--coseek1_persistent_candidate_pool_timestamp_radius_s", type=float, default=general_config.get('coseek1_persistent_candidate_pool_timestamp_radius_s'), help="Context radius around promoted Overview timestamp cues.")
    p.add_argument("--coseek1_candidate_evidence_projection", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_candidate_evidence_projection'), help="Show representative scene facts and compact redundant search targets without changing routing policy.")
    p.add_argument("--coseek1_temporal_evidence_ledger_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_temporal_evidence_ledger_enabled'), help="Expose stable deduplicated frame-verifier event spans to the planner.")
    p.add_argument("--coseek1_temporal_evidence_ledger_max_events", type=int, default=general_config.get('coseek1_temporal_evidence_ledger_max_events'))
    p.add_argument("--coseek1_verified_observation_reuse_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_verified_observation_reuse_enabled'), help="Reuse semantically equivalent frame verification over the same pixels.")
    p.add_argument("--coseek1_verified_observation_reuse_overlap", type=float, default=general_config.get('coseek1_verified_observation_reuse_overlap'))
    p.add_argument("--coseek1_verified_observation_reuse_query_similarity", type=float, default=general_config.get('coseek1_verified_observation_reuse_query_similarity'))
    p.add_argument("--coseek1_semantic_gap_resolution_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_semantic_gap_resolution_enabled'), help="Resolve open evidence gaps only when target binding, scope, and remaining-need semantics agree.")
    p.add_argument("--coseek1_observer_conflict_memory_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_observer_conflict_memory_enabled'), help="Expose verified support/contradiction conflicts without blocking planner actions.")
    p.add_argument("--coseek1_direct_planner_answer", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_direct_planner_answer'), help="Return a valid planner-selected option locally instead of calling the answer API again.")
    p.add_argument("--coseek1_localize_qwen_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_localize_qwen_enabled'), help="Expose hierarchical localize_qwen planner semantics.")
    p.add_argument("--localize_qwen_top_k", type=int, default=general_config.get('localize_qwen_top_k'))
    p.add_argument("--localize_qwen_max_top_k", type=int, default=general_config.get('localize_qwen_max_top_k'))
    p.add_argument("--localize_qwen_row_candidate_windows", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_row_candidate_windows'), help="Derive localize candidates from merged medium/high timestamp captions.")
    p.add_argument("--localize_qwen_cover_search_windows", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_cover_search_windows'), help="Allow one retained candidate per independent search window up to max_top_k.")
    p.add_argument("--localize_qwen_max_search_windows", type=int, default=general_config.get('localize_qwen_max_search_windows'))
    p.add_argument("--coseek1_tool_integrity_repair_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_tool_integrity_repair_enabled'), help="Preserve exact trajectory timestamps and requested-window coverage across visual tools.")
    p.add_argument("--coseek1_tool_memory_anchor_margin_s", type=float, default=general_config.get('coseek1_tool_memory_anchor_margin_s'))
    p.add_argument("--coseek1_tool_memory_anchors_per_window", type=int, default=general_config.get('coseek1_tool_memory_anchors_per_window'))
    p.add_argument("--coseek1_tool_memory_anchor_pad_s", type=float, default=general_config.get('coseek1_tool_memory_anchor_pad_s'))
    p.add_argument("--coseek1_tool_event_identity_repair_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_tool_event_identity_repair_enabled'), help="Do not treat temporal packet clusters as verified semantic event identities.")
    p.add_argument("--coseek1_tool_recollect_expanded_anchors_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_tool_recollect_expanded_anchors_enabled'), help="Recollect existing trajectory anchors after localize boundary expansion.")
    p.add_argument("--grounded_verify_packet_boundary_context_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_verify_packet_boundary_context_enabled'), help="Use a complementary post/boundary detail anchor without increasing packet image count.")
    p.add_argument("--localize_qwen_coarse_max_frames", type=int, default=general_config.get('localize_qwen_coarse_max_frames'))
    p.add_argument("--localize_qwen_fine_max_frames", type=int, default=general_config.get('localize_qwen_fine_max_frames'))
    p.add_argument("--localize_qwen_verify_window_s", type=float, default=general_config.get('localize_qwen_verify_window_s'))
    p.add_argument("--localize_qwen_verify_context_margin_s", type=float, default=general_config.get('localize_qwen_verify_context_margin_s'))
    p.add_argument("--localize_qwen_search_context_margin_s", type=float, default=general_config.get('localize_qwen_search_context_margin_s'))
    p.add_argument("--localize_qwen_adaptive_search_context", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_adaptive_search_context'))
    p.add_argument("--localize_qwen_normalized_candidate_score_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_normalized_candidate_score_enabled'), help="Rank local candidates with density-normalized relevance and continuity.")
    p.add_argument("--localize_qwen_duration_budget_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_duration_budget_enabled'))
    p.add_argument("--localize_qwen_duration_budget_fps", type=float, default=general_config.get('localize_qwen_duration_budget_fps'))
    p.add_argument("--localize_qwen_duration_budget_min_frames", type=int, default=general_config.get('localize_qwen_duration_budget_min_frames'))
    p.add_argument("--localize_qwen_duration_budget_max_frames", type=int, default=general_config.get('localize_qwen_duration_budget_max_frames'))
    p.add_argument("--localize_qwen_codec_anchor_sampling_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_codec_anchor_sampling_enabled'))
    p.add_argument("--localize_qwen_boundary_expansion_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_boundary_expansion_enabled'))
    p.add_argument("--localize_qwen_boundary_context_margin_s", type=float, default=general_config.get('localize_qwen_boundary_context_margin_s'))
    p.add_argument("--localize_qwen_boundary_trigger_s", type=float, default=general_config.get('localize_qwen_boundary_trigger_s'))
    p.add_argument("--localize_qwen_boundary_expansion_max_frames", type=int, default=general_config.get('localize_qwen_boundary_expansion_max_frames'))
    p.add_argument("--localize_qwen_caption_cache_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_caption_cache_enabled'))
    p.add_argument("--localize_qwen_caption_cache_goal_similarity", type=float, default=general_config.get('localize_qwen_caption_cache_goal_similarity'))
    p.add_argument("--localize_qwen_caption_cache_coverage_ratio", type=float, default=general_config.get('localize_qwen_caption_cache_coverage_ratio'))
    p.add_argument("--localize_qwen_candidate_novelty_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_candidate_novelty_enabled'))
    p.add_argument("--localize_qwen_candidate_novelty_overlap", type=float, default=general_config.get('localize_qwen_candidate_novelty_overlap'))
    p.add_argument("--localize_qwen_strict_evidence_status_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_strict_evidence_status_enabled'))
    p.add_argument("--localize_qwen_trace_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('localize_qwen_trace_enabled'))
    p.add_argument("--coseek1_localize_inline_verify", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_localize_inline_verify'))
    p.add_argument("--localize_inline_verify_max_windows", type=int, default=general_config.get('localize_inline_verify_max_windows'))
    p.add_argument("--localize_inline_verify_max_frames", type=int, default=general_config.get('localize_inline_verify_max_frames'))
    p.add_argument("--localize_inline_verify_contact_sheets", action=argparse.BooleanOptionalAction, default=general_config.get('localize_inline_verify_contact_sheets'), help="Pack each candidate's ordered verification frames into one timestamped contact sheet.")
    p.add_argument("--multiwindow_verify_recovery_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('multiwindow_verify_recovery_enabled'), help="Retry only candidate windows omitted by multi-window verification.")
    p.add_argument("--multiwindow_verify_recovery_max_calls", type=int, default=general_config.get('multiwindow_verify_recovery_max_calls'), help="Maximum internal recovery requests per multi-window verification.")
    p.add_argument("--multiwindow_verify_recovery_batch_size", type=int, default=general_config.get('multiwindow_verify_recovery_batch_size'), help="Missing candidate windows per internal recovery request.")
    p.add_argument("--grounded_frame_verify_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_frame_verify_enabled'), help="Use local spatial grounding before remote frame verification.")
    p.add_argument("--grounded_high_recall_proposal_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_high_recall_proposal_enabled'), help="Ask local grounding for a plausible visual referent without deciding the answer.")
    p.add_argument("--grounded_verify_packet_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_verify_packet_enabled'), help="Send one temporal sheet plus one detail image per candidate.")
    p.add_argument("--packet_detail_grounding_escalation_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('packet_detail_grounding_escalation_enabled'), help="Allow one candidate-bound local crop retry when Packet verification explicitly lacks a small visual detail.")
    p.add_argument("--packet_detail_grounding_escalation_frames", type=int, default=general_config.get('packet_detail_grounding_escalation_frames'), help="Temporal-frame budget for the one-anchor adaptive detail retry.")
    p.add_argument("--packet_adaptive_evidence_need_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('packet_adaptive_evidence_need_enabled'), help="Classify unresolved verification evidence as spatial, temporal, semantic, conflict, or sufficient.")
    p.add_argument("--packet_detail_grounding_direct_escalation_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('packet_detail_grounding_direct_escalation_enabled'), help="Allow direct Packet verification to use the same one-anchor spatial-detail escalation.")
    p.add_argument("--grounded_verify_packet_anchors_per_candidate", type=int, default=general_config.get('grounded_verify_packet_anchors_per_candidate'), help="Maximum grounded detail anchors packed into each candidate detail image.")
    p.add_argument("--grounded_verify_packet_temporal_anchor_spread_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_verify_packet_temporal_anchor_spread_enabled'), help="Distribute fixed packet detail anchors across the localized evidence span.")
    p.add_argument("--grounded_verify_packet_crop_max_side", type=int, default=general_config.get('grounded_verify_packet_crop_max_side'), help="Maximum long side of a grounded detail crop.")
    p.add_argument("--grounded_verify_packet_peak_max_side", type=int, default=general_config.get('grounded_verify_packet_peak_max_side'), help="Maximum long side of the fallback detail anchor.")
    p.add_argument("--grounded_direct_verify_packet_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_direct_verify_packet_enabled'), help="Pack a direct short-window verify into ordered temporal sheets plus one detail sheet.")
    p.add_argument("--grounded_direct_verify_packet_group_size", type=int, default=general_config.get('grounded_direct_verify_packet_group_size'), help="Maximum source frames in each direct temporal sheet.")
    p.add_argument("--grounded_direct_verify_packet_anchor_count", type=int, default=general_config.get('grounded_direct_verify_packet_anchor_count'), help="High-resolution anchors retained for a direct verify packet.")
    p.add_argument("--grounded_direct_verify_packet_detail_max_side", type=int, default=general_config.get('grounded_direct_verify_packet_detail_max_side'), help="Maximum long side of each direct detail tile.")
    p.add_argument("--grounded_candidate_binding_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_candidate_binding_enabled'), help="Preserve a separate target-binding assessment for every verified candidate window.")
    p.add_argument("--grounded_candidate_event_binding_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('grounded_candidate_event_binding_enabled'), help="Keep exact-event evidence separate from same-entity context in another episode.")
    p.add_argument("--grounded_candidate_event_group_max_gap_s", type=float, default=general_config.get('grounded_candidate_event_group_max_gap_s'), help="Maximum temporal gap for candidate windows to share one event group.")
    p.add_argument("--packet_decision_consistency_normalization_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('packet_decision_consistency_normalization_enabled'), help="Normalize internally inconsistent verifier sufficiency when the option comparison is already complete.")
    p.add_argument("--packet_multiwindow_decision_sufficiency_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('packet_multiwindow_decision_sufficiency_enabled'), help="Separate complete multi-window option discrimination from optional residual visual detail.")
    p.add_argument("--coseek1_frontier_temporal_boundaries", action=argparse.BooleanOptionalAction, default=general_config.get('coseek1_frontier_temporal_boundaries'), help="Expose unresolved continuity relationships between nearby timestamp cues.")
    p.add_argument("--coseek1_frontier_temporal_boundary_max_gap_s", type=float, default=general_config.get('coseek1_frontier_temporal_boundary_max_gap_s'), help="Maximum gap used to surface a temporal continuity check.")
    p.add_argument("--direct_answer_from_letter_thought", action=argparse.BooleanOptionalAction, default=general_config.get('direct_answer_from_letter_thought'), help="If the model thought is exactly A/B/C/D, call answer directly instead of reparsing tools.")
    p.add_argument("--extract_explicit_thought_action", action=argparse.BooleanOptionalAction, default=general_config.get('extract_explicit_thought_action'), help="Parse explicit Next action / Tool Call text from the model thought.")
    p.add_argument("--prefer_explicit_thought_action", action=argparse.BooleanOptionalAction, default=general_config.get('prefer_explicit_thought_action'), help="Use explicit thought actions when secondary parsing returns no observation action.")
    p.add_argument("--require_scene_skim_before_focus", action=argparse.BooleanOptionalAction, default=general_config.get('require_scene_skim_before_focus'), help="Auto-insert a scene skim before direct focus when a matched scene has no skim observation.")
    p.add_argument("--pre_focus_skim_context_s", type=float, default=general_config.get('pre_focus_skim_context_s'), help="Seconds to expand around a focus window for auto pre-focus skim.")
    p.add_argument("--pre_focus_skim_max_window_s", type=float, default=general_config.get('pre_focus_skim_max_window_s'), help="Maximum auto pre-focus skim window length.")
    p.add_argument("--qwen_first_observer", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_first_observer'), help="Route eligible skim/focus actions to local Qwen first.")
    p.add_argument("--qwen_first_skim", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_first_skim'), help="Allow Qwen-first routing for skim.")
    p.add_argument("--qwen_first_focus", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_first_focus'), help="Allow Qwen-first routing for focus.")
    p.add_argument("--qwen_first_skim_modes", default=general_config.get('qwen_first_skim_modes'), help="Comma-separated skim modes eligible for Qwen-first routing.")
    p.add_argument("--qwen_first_focus_modes", default=general_config.get('qwen_first_focus_modes'), help="Comma-separated focus modes eligible for Qwen-first routing.")
    p.add_argument("--qwen_first_skim_max_window_s", type=float, default=general_config.get('qwen_first_skim_max_window_s'), help="Maximum skim window length routed to Qwen-first.")
    p.add_argument("--qwen_first_focus_max_window_s", type=float, default=general_config.get('qwen_first_focus_max_window_s'), help="Maximum focus window length routed to Qwen-first.")
    p.add_argument("--qwen_first_verify_uncertain_skim", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_first_verify_uncertain_skim'), help="Verify uncertain skim_qwen observations with API skim.")
    p.add_argument("--qwen_first_verify_uncertain_focus", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_first_verify_uncertain_focus'), help="Verify uncertain focus_qwen observations with API focus.")
    p.add_argument("--qwen_first_verify_parse_error", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_first_verify_parse_error'), help="Verify local Qwen parse errors or local failures with API.")
    p.add_argument("--qwen_first_repeat_window_escalates_to_api", action=argparse.BooleanOptionalAction, default=general_config.get('qwen_first_repeat_window_escalates_to_api'), help="If the agent asks for a similar window after a Qwen observation, keep the repeated request on API.")
    p.add_argument("--qwen_first_skim_api_relevance_threshold", type=float, default=general_config.get('qwen_first_skim_api_relevance_threshold'), help="Low relevance threshold for optional skim_qwen API verification.")
    p.add_argument("--focus_context_pad_s", type=float, default=general_config.get('focus_context_pad_s'), help="Seconds of context to add before and after each focus window.")
    p.add_argument("--focus_qwen_max_frames", type=int, default=general_config.get('focus_qwen_max_frames'), help="Maximum frames for focus_qwen.")
    p.add_argument("--focus_qwen_context_pad_s", type=float, default=general_config.get('focus_qwen_context_pad_s'), help="Seconds of context to add before and after focus_qwen windows.")
    p.add_argument("--focus_qwen_max_window_s", type=float, default=general_config.get('focus_qwen_max_window_s'), help="Maximum post-padding focus_qwen window length.")
    p.add_argument("--focus_qwen_short_side", type=int, default=general_config.get('focus_qwen_short_side'), help="Short-side resize for focus_qwen cells.")
    p.add_argument("--focus_qwen_max_new_tokens", type=int, default=general_config.get('focus_qwen_max_new_tokens'), help="Max new tokens for compact focus_qwen.")
    p.add_argument("--focus_qwen_fallback_to_api", action=argparse.BooleanOptionalAction, default=general_config.get('focus_qwen_fallback_to_api'), help="Fallback to API if focus_qwen fails.")
    p.add_argument("--focus_qwen_frame_caption_words", type=int, default=general_config.get('focus_qwen_frame_caption_words'), help="Per-frame caption word budget for focus_qwen.")
    p.add_argument("--focus_qwen_summary_words", type=int, default=general_config.get('focus_qwen_summary_words'), help="Summary word budget for focus_qwen.")
    p.add_argument("--skim_long_window_s", type=float, default=general_config.get('skim_long_window_s'), help="Use expanded skim sampling for windows at least this long.")
    p.add_argument("--skim_long_num_frames", type=int, default=general_config.get('skim_long_num_frames'), help="Maximum frames for expanded long-window skim.")
    p.add_argument("--skim_long_target_step_s", type=float, default=general_config.get('skim_long_target_step_s'), help="Approximate seconds per sampled frame for expanded long-window skim.")
    p.add_argument("--skim_qwen_max_frames", type=int, default=general_config.get('skim_qwen_max_frames'), help="Maximum frames for skim_qwen.")
    p.add_argument("--skim_qwen_short_side", type=int, default=general_config.get('skim_qwen_short_side'), help="Short-side resize for skim_qwen cells.")
    p.add_argument("--skim_qwen_max_new_tokens", type=int, default=general_config.get('skim_qwen_max_new_tokens'), help="Max new tokens for compact skim_qwen.")
    p.add_argument("--skim_qwen_recommended_max_window_s", type=float, default=general_config.get('skim_qwen_recommended_max_window_s'), help="Recommended maximum window length for skim_qwen.")
    p.add_argument("--skim_qwen_fallback_to_api", action=argparse.BooleanOptionalAction, default=general_config.get('skim_qwen_fallback_to_api'), help="Fallback to API if skim_qwen fails.")
    p.add_argument("--skim_qwen_frame_caption_words", type=int, default=general_config.get('skim_qwen_frame_caption_words'), help="Per-frame caption word budget for skim_qwen.")
    p.add_argument("--skim_qwen_relevant_detail_words", type=int, default=general_config.get('skim_qwen_relevant_detail_words'), help="Extra evidence detail word budget for relevant skim_qwen frames.")
    p.add_argument("--skim_qwen_window_summary_words", type=int, default=general_config.get('skim_qwen_window_summary_words'), help="Window summary word budget for skim_qwen.")
    p.add_argument("--use_skeleton_overview", action=argparse.BooleanOptionalAction, default=general_config.get('use_skeleton_overview'), help="Use offline codec skeleton memory for overview.")
    p.add_argument("--scene_aware_skim", action=argparse.BooleanOptionalAction, default=general_config.get('scene_aware_skim'), help="Attach matched skeleton scene memory to skim and skim_qwen.")
    p.add_argument("--skeleton_cache_dir", default=general_config.get('skeleton_cache_dir'), help="Directory for cached skeleton memory.")
    p.add_argument("--skeleton_scene_min_s", type=float, default=general_config.get('skeleton_scene_min_s'), help="Minimum virtual scene/window length.")
    p.add_argument("--skeleton_scene_max_s", type=float, default=general_config.get('skeleton_scene_max_s'), help="Maximum virtual scene/window length before forced split.")
    p.add_argument("--skeleton_max_scenes", type=int, default=general_config.get('skeleton_max_scenes'), help="Maximum number of skeleton scenes.")
    p.add_argument("--skeleton_anchors_per_scene", type=int, default=general_config.get('skeleton_anchors_per_scene'), help="Anchor timestamps per skeleton scene.")
    p.add_argument("--skeleton_caption_enabled", action=argparse.BooleanOptionalAction, default=general_config.get('skeleton_caption_enabled'), help="Generate visual captions for skeleton scenes when cache is missing.")
    p.add_argument("--skeleton_caption_strategy", default=general_config.get('skeleton_caption_strategy'), help="Skeleton caption strategy: contact_sheet, single_frame, or mini_sheet_tags.")
    p.add_argument("--skeleton_caption_frames", type=int, default=general_config.get('skeleton_caption_frames'), help="Maximum frames used to caption a skeleton.")
    p.add_argument("--skeleton_caption_frames_per_scene", type=int, default=general_config.get('skeleton_caption_frames_per_scene'), help="Maximum prioritized caption frames per skeleton scene before global cap.")
    p.add_argument("--skeleton_caption_scenes_per_chunk", type=int, default=general_config.get('skeleton_caption_scenes_per_chunk'), help="Number of skeleton scenes captioned per API chunk.")
    p.add_argument("--skeleton_caption_retries", type=int, default=general_config.get('skeleton_caption_retries'), help="Retries for offline skeleton caption generation.")
    p.add_argument("--skeleton_caption_retry_failed_cache", action=argparse.BooleanOptionalAction, default=general_config.get('skeleton_caption_retry_failed_cache'), help="Retry caption generation even if cached skeleton records a previous caption failure.")
    p.add_argument("--skeleton_caption_short_side", type=int, default=general_config.get('skeleton_caption_short_side'), help="Short-side resize for skeleton caption frames.")
    p.add_argument("--skeleton_single_frame_short_side", type=int, default=general_config.get('skeleton_single_frame_short_side'), help="Short-side resize for single-frame skeleton caption.")
    p.add_argument("--skeleton_single_frame_aggregate", action=argparse.BooleanOptionalAction, default=general_config.get('skeleton_single_frame_aggregate'), help="Use API text aggregation for single-frame skeleton captions.")
    p.add_argument("--skeleton_mini_sheet_group_size", type=int, default=general_config.get('skeleton_mini_sheet_group_size'), help="Frames per mini-sheet for short-tag skeleton caption, capped at 4.")
    p.add_argument("--skeleton_mini_sheet_short_side", type=int, default=general_config.get('skeleton_mini_sheet_short_side'), help="Short-side resize for each mini-sheet cell.")
    p.add_argument("--skeleton_overview_max_scenes", type=int, default=general_config.get('skeleton_overview_max_scenes'), help="Maximum skeleton scenes included in overview prompt.")
    return p.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    config = build_agent_config(args)

    video_id = args.video_path.split("/")[-1].split(".")[0]

    run_id = f"{video_id}_{int(time.time())}"
    run_dir = output_dir / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    # Run the agent
    agent = VideoSeekAgent(
        config=config,
        video_path=args.video_path,
        subtitle_path=args.subtitle_path,
        output_dir=str(output_dir),
        tools=config["tools"],
        verbose=args.verbose,
    )
    traj = agent.run(args.user_query)
    traj_dict = traj.to_dict()
    prediction = traj_dict.get("final_answer", "")

    print(f"Question: {args.user_query}")
    print(f"Prediction: {prediction}")

    (run_dir / "prediction.json").write_text(json.dumps({"prediction": prediction}, ensure_ascii=False, indent=2), encoding="utf-8")
    (run_dir / "trajectory.json").write_text(json.dumps(traj_dict, ensure_ascii=False, indent=2), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
